# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.v1alpha1_config_map_key_ref import V1alpha1ConfigMapKeyRef  # noqa: E501
from pyargocd.rest import ApiException


class TestV1alpha1ConfigMapKeyRef(unittest.TestCase):
    """V1alpha1ConfigMapKeyRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1ConfigMapKeyRef(self):
        """Test V1alpha1ConfigMapKeyRef"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.v1alpha1_config_map_key_ref.V1alpha1ConfigMapKeyRef()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
