# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.runtime_stream_error import RuntimeStreamError  # noqa: E501
from pyargocd.rest import ApiException


class TestRuntimeStreamError(unittest.TestCase):
    """RuntimeStreamError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuntimeStreamError(self):
        """Test RuntimeStreamError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.runtime_stream_error.RuntimeStreamError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
