# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.applicationv1alpha1_resource_status import Applicationv1alpha1ResourceStatus  # noqa: E501
from pyargocd.rest import ApiException


class TestApplicationv1alpha1ResourceStatus(unittest.TestCase):
    """Applicationv1alpha1ResourceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationv1alpha1ResourceStatus(self):
        """Test Applicationv1alpha1ResourceStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.applicationv1alpha1_resource_status.Applicationv1alpha1ResourceStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
