# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.cluster_cluster_id import ClusterClusterID  # noqa: E501
from pyargocd.rest import ApiException


class TestClusterClusterID(unittest.TestCase):
    """ClusterClusterID unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusterClusterID(self):
        """Test ClusterClusterID"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.cluster_cluster_id.ClusterClusterID()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
