# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.v1alpha1_dry_source import V1alpha1DrySource  # noqa: E501
from pyargocd.rest import ApiException


class TestV1alpha1DrySource(unittest.TestCase):
    """V1alpha1DrySource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1DrySource(self):
        """Test V1alpha1DrySource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.v1alpha1_dry_source.V1alpha1DrySource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
