# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.v1alpha1_source_hydrator_status import V1alpha1SourceHydratorStatus  # noqa: E501
from pyargocd.rest import ApiException


class TestV1alpha1SourceHydratorStatus(unittest.TestCase):
    """V1alpha1SourceHydratorStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1SourceHydratorStatus(self):
        """Test V1alpha1SourceHydratorStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.v1alpha1_source_hydrator_status.V1alpha1SourceHydratorStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
