# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.v1alpha1_bearer_token_bitbucket import V1alpha1BearerTokenBitbucket  # noqa: E501
from pyargocd.rest import ApiException


class TestV1alpha1BearerTokenBitbucket(unittest.TestCase):
    """V1alpha1BearerTokenBitbucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alpha1BearerTokenBitbucket(self):
        """Test V1alpha1BearerTokenBitbucket"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.v1alpha1_bearer_token_bitbucket.V1alpha1BearerTokenBitbucket()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
