# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.applicationset_application_set_generate_request import ApplicationsetApplicationSetGenerateRequest  # noqa: E501
from pyargocd.rest import ApiException


class TestApplicationsetApplicationSetGenerateRequest(unittest.TestCase):
    """ApplicationsetApplicationSetGenerateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationsetApplicationSetGenerateRequest(self):
        """Test ApplicationsetApplicationSetGenerateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.applicationset_application_set_generate_request.ApplicationsetApplicationSetGenerateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
