# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.models.account_accounts_list import AccountAccountsList  # noqa: E501
from pyargocd.rest import ApiException


class TestAccountAccountsList(unittest.TestCase):
    """AccountAccountsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountAccountsList(self):
        """Test AccountAccountsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyargocd.models.account_accounts_list.AccountAccountsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
