# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyargocd
from pyargocd.api.repo_creds_service_api import RepoCredsServiceApi  # noqa: E501
from pyargocd.rest import ApiException


class TestRepoCredsServiceApi(unittest.TestCase):
    """RepoCredsServiceApi unit test stubs"""

    def setUp(self):
        self.api = pyargocd.api.repo_creds_service_api.RepoCredsServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_repo_creds_service_create_repository_credentials(self):
        """Test case for repo_creds_service_create_repository_credentials

        CreateRepositoryCredentials creates a new repository credential set  # noqa: E501
        """
        pass

    def test_repo_creds_service_create_write_repository_credentials(self):
        """Test case for repo_creds_service_create_write_repository_credentials

        CreateWriteRepositoryCredentials creates a new repository credential set with write access  # noqa: E501
        """
        pass

    def test_repo_creds_service_delete_repository_credentials(self):
        """Test case for repo_creds_service_delete_repository_credentials

        DeleteRepositoryCredentials deletes a repository credential set from the configuration  # noqa: E501
        """
        pass

    def test_repo_creds_service_delete_write_repository_credentials(self):
        """Test case for repo_creds_service_delete_write_repository_credentials

        DeleteWriteRepositoryCredentials deletes a repository credential set with write access from the configuration  # noqa: E501
        """
        pass

    def test_repo_creds_service_list_repository_credentials(self):
        """Test case for repo_creds_service_list_repository_credentials

        ListRepositoryCredentials gets a list of all configured repository credential sets  # noqa: E501
        """
        pass

    def test_repo_creds_service_list_write_repository_credentials(self):
        """Test case for repo_creds_service_list_write_repository_credentials

        ListWriteRepositoryCredentials gets a list of all configured repository credential sets that have write access  # noqa: E501
        """
        pass

    def test_repo_creds_service_update_repository_credentials(self):
        """Test case for repo_creds_service_update_repository_credentials

        UpdateRepositoryCredentials updates a repository credential set  # noqa: E501
        """
        pass

    def test_repo_creds_service_update_write_repository_credentials(self):
        """Test case for repo_creds_service_update_write_repository_credentials

        UpdateWriteRepositoryCredentials updates a repository credential set with write access  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
