# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from argocd.configuration import Configuration


class V1alpha1DrySource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'repo_url': 'str',
        'target_revision': 'str'
    }

    attribute_map = {
        'path': 'path',
        'repo_url': 'repoURL',
        'target_revision': 'targetRevision'
    }

    def __init__(self, path=None, repo_url=None, target_revision=None, _configuration=None):  # noqa: E501
        """V1alpha1DrySource - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._path = None
        self._repo_url = None
        self._target_revision = None
        self.discriminator = None

        if path is not None:
            self.path = path
        if repo_url is not None:
            self.repo_url = repo_url
        if target_revision is not None:
            self.target_revision = target_revision

    @property
    def path(self):
        """Gets the path of this V1alpha1DrySource.  # noqa: E501


        :return: The path of this V1alpha1DrySource.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this V1alpha1DrySource.


        :param path: The path of this V1alpha1DrySource.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def repo_url(self):
        """Gets the repo_url of this V1alpha1DrySource.  # noqa: E501


        :return: The repo_url of this V1alpha1DrySource.  # noqa: E501
        :rtype: str
        """
        return self._repo_url

    @repo_url.setter
    def repo_url(self, repo_url):
        """Sets the repo_url of this V1alpha1DrySource.


        :param repo_url: The repo_url of this V1alpha1DrySource.  # noqa: E501
        :type: str
        """

        self._repo_url = repo_url

    @property
    def target_revision(self):
        """Gets the target_revision of this V1alpha1DrySource.  # noqa: E501


        :return: The target_revision of this V1alpha1DrySource.  # noqa: E501
        :rtype: str
        """
        return self._target_revision

    @target_revision.setter
    def target_revision(self, target_revision):
        """Sets the target_revision of this V1alpha1DrySource.


        :param target_revision: The target_revision of this V1alpha1DrySource.  # noqa: E501
        :type: str
        """

        self._target_revision = target_revision

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1DrySource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1DrySource):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1DrySource):
            return True

        return self.to_dict() != other.to_dict()
