# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from argocd.configuration import Configuration


class V1alpha1SourceHydratorStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'current_operation': 'V1alpha1HydrateOperation',
        'last_successful_operation': 'V1alpha1SuccessfulHydrateOperation'
    }

    attribute_map = {
        'current_operation': 'currentOperation',
        'last_successful_operation': 'lastSuccessfulOperation'
    }

    def __init__(self, current_operation=None, last_successful_operation=None, _configuration=None):  # noqa: E501
        """V1alpha1SourceHydratorStatus - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._current_operation = None
        self._last_successful_operation = None
        self.discriminator = None

        if current_operation is not None:
            self.current_operation = current_operation
        if last_successful_operation is not None:
            self.last_successful_operation = last_successful_operation

    @property
    def current_operation(self):
        """Gets the current_operation of this V1alpha1SourceHydratorStatus.  # noqa: E501


        :return: The current_operation of this V1alpha1SourceHydratorStatus.  # noqa: E501
        :rtype: V1alpha1HydrateOperation
        """
        return self._current_operation

    @current_operation.setter
    def current_operation(self, current_operation):
        """Sets the current_operation of this V1alpha1SourceHydratorStatus.


        :param current_operation: The current_operation of this V1alpha1SourceHydratorStatus.  # noqa: E501
        :type: V1alpha1HydrateOperation
        """

        self._current_operation = current_operation

    @property
    def last_successful_operation(self):
        """Gets the last_successful_operation of this V1alpha1SourceHydratorStatus.  # noqa: E501


        :return: The last_successful_operation of this V1alpha1SourceHydratorStatus.  # noqa: E501
        :rtype: V1alpha1SuccessfulHydrateOperation
        """
        return self._last_successful_operation

    @last_successful_operation.setter
    def last_successful_operation(self, last_successful_operation):
        """Sets the last_successful_operation of this V1alpha1SourceHydratorStatus.


        :param last_successful_operation: The last_successful_operation of this V1alpha1SourceHydratorStatus.  # noqa: E501
        :type: V1alpha1SuccessfulHydrateOperation
        """

        self._last_successful_operation = last_successful_operation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1SourceHydratorStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1SourceHydratorStatus):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1SourceHydratorStatus):
            return True

        return self.to_dict() != other.to_dict()
