# coding: utf-8

"""
    Consolidate Services

    Description of all APIs  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from argocd.configuration import Configuration


class V1alpha1SuccessfulHydrateOperation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'dry_sha': 'str',
        'hydrated_sha': 'str',
        'source_hydrator': 'V1alpha1SourceHydrator'
    }

    attribute_map = {
        'dry_sha': 'drySHA',
        'hydrated_sha': 'hydratedSHA',
        'source_hydrator': 'sourceHydrator'
    }

    def __init__(self, dry_sha=None, hydrated_sha=None, source_hydrator=None, _configuration=None):  # noqa: E501
        """V1alpha1SuccessfulHydrateOperation - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._dry_sha = None
        self._hydrated_sha = None
        self._source_hydrator = None
        self.discriminator = None

        if dry_sha is not None:
            self.dry_sha = dry_sha
        if hydrated_sha is not None:
            self.hydrated_sha = hydrated_sha
        if source_hydrator is not None:
            self.source_hydrator = source_hydrator

    @property
    def dry_sha(self):
        """Gets the dry_sha of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501


        :return: The dry_sha of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501
        :rtype: str
        """
        return self._dry_sha

    @dry_sha.setter
    def dry_sha(self, dry_sha):
        """Sets the dry_sha of this V1alpha1SuccessfulHydrateOperation.


        :param dry_sha: The dry_sha of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501
        :type: str
        """

        self._dry_sha = dry_sha

    @property
    def hydrated_sha(self):
        """Gets the hydrated_sha of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501


        :return: The hydrated_sha of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501
        :rtype: str
        """
        return self._hydrated_sha

    @hydrated_sha.setter
    def hydrated_sha(self, hydrated_sha):
        """Sets the hydrated_sha of this V1alpha1SuccessfulHydrateOperation.


        :param hydrated_sha: The hydrated_sha of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501
        :type: str
        """

        self._hydrated_sha = hydrated_sha

    @property
    def source_hydrator(self):
        """Gets the source_hydrator of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501


        :return: The source_hydrator of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501
        :rtype: V1alpha1SourceHydrator
        """
        return self._source_hydrator

    @source_hydrator.setter
    def source_hydrator(self, source_hydrator):
        """Sets the source_hydrator of this V1alpha1SuccessfulHydrateOperation.


        :param source_hydrator: The source_hydrator of this V1alpha1SuccessfulHydrateOperation.  # noqa: E501
        :type: V1alpha1SourceHydrator
        """

        self._source_hydrator = source_hydrator

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(V1alpha1SuccessfulHydrateOperation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1alpha1SuccessfulHydrateOperation):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1alpha1SuccessfulHydrateOperation):
            return True

        return self.to_dict() != other.to_dict()
